"""Preserve four controlled Mesen calls and emit their C binding inputs."""
import argparse
import base64
import hashlib
import json
from pathlib import Path
import zlib

GLOBALS = [0x7F6, 0x92E, 0x936, 0x93E, 0x942, 0x944, 0x946, 0x948,
           0x952, 0x954, 0x958, 0x95A, 0x95C, 0x964, 0x968, 0x978,
           0x996, 0x9B6, 0x9B8, 0x9BA, 0x9C4, 0x9F6, 0xA08]
ACTOR = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0x16, 0x28, 0x2A, 0x2C,
         0x30, 0x32, 0x38, 0x3A, 0x3C, 0x4C, 0x4E, 0x50, 0x52, 0x56,
         0x58, 0x5E, 0x60, 0x74, 0x76, 0x7E, 0xA8, 0x72]


def word(memory, address):
    return int.from_bytes(memory[address:address + 2], "little")


def projected(row):
    before = bytes.fromhex(row["entry"]["mem"]["0000"])
    after = bytes.fromhex(row["exit"]["mem"]["0000"])
    actor = word(before, 0x96)
    expected = [word(after, a) for a in
                (0x968, 0x9F6, actor + 0x7E, actor + 0xE, actor + 0x10,
                 0x9BA, 0x9B6, 0x964, 0x9B8, actor + 0x4E)]
    return ([word(before, a) for a in GLOBALS],
            [word(before, actor + o) for o in ACTOR], expected,
            [word(before, a) for a in range(0x3EED, 0x3EFE, 2)])


def header(calls):
    text = ["/* Generated by normalize_inbound_cancel_recovery.py. Native",
            " * full-memory provenance is in inbound-cancel-recovery.json.",
            " * The ten outputs project F54F-F587; DP/stack/NMI and the",
            " * preceding steering prefix are intentionally not compared. */",
            "typedef struct { unsigned frame; uint16_t globals[23], actor[32],",
            "    expected[10], ball[9]; } InboundCancelWitness;",
            "static const InboundCancelWitness inbound_cancel_witnesses[] = {"]
    for row in calls:
        values = projected(row)
        text.append("    {%du, %s}," % (row["entry_frame"], ", ".join(
            "{" + ",".join("0x%04x" % value for value in array) + "}"
            for array in values)))
    text.append("};")
    return "\n".join(text) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--capture-dir", required=True, type=Path)
    parser.add_argument("--fixture", required=True, type=Path)
    parser.add_argument("--header", required=True, type=Path)
    args = parser.parse_args()
    raw = (args.capture_dir / "inbound-cancel-recovery.jsonl").read_bytes()
    meta = json.loads((args.capture_dir / "inbound-cancel-recovery.meta.json").read_text(encoding="utf-8-sig"))
    assert hashlib.sha256(raw).hexdigest() == meta["vectors_sha256"]
    calls = [json.loads(line) for line in raw.splitlines()]
    assert len(calls) == 4
    args.header.write_text(header(calls), encoding="utf-8")
    # Lossless compression retains every captured byte, including the NMI
    # writes in case3; it is not a reduced or C-generated expected result.
    args.fixture.write_text(json.dumps({"schema": 1, "provenance": meta,
        "source": str(args.capture_dir / "inbound-cancel-recovery.jsonl"),
        "raw_jsonl_zlib_base64": base64.b64encode(zlib.compress(raw, 9)).decode(),
        "globals": GLOBALS, "actor_offsets": ACTOR,
        "case_frames": [row["entry_frame"] for row in calls]}, indent=2) + "\n", encoding="utf-8")
    print("normalized four controlled native cancellation calls")


if __name__ == "__main__":
    main()
